//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spotmap.Webservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.spotmap.de/", ConfigurationName="Spotmap.Webservice.ISpotShare")]
    public interface ISpotShare {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginshareSpot(Spotmap.Webservice.shareSpotRequest request, System.AsyncCallback callback, object asyncState);
        
        Spotmap.Webservice.shareSpotResponse EndshareSpot(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BegingetSharedSpot(Spotmap.Webservice.getSharedSpotRequest request, System.AsyncCallback callback, object asyncState);
        
        Spotmap.Webservice.getSharedSpotResponse EndgetSharedSpot(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginshareSpots(Spotmap.Webservice.shareSpotsRequest request, System.AsyncCallback callback, object asyncState);
        
        Spotmap.Webservice.shareSpotsResponse EndshareSpots(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BegingetSharedSpots(Spotmap.Webservice.getSharedSpotsRequest request, System.AsyncCallback callback, object asyncState);
        
        Spotmap.Webservice.getSharedSpotsResponse EndgetSharedSpots(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.spotmap.de/")]
    public partial class spot : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private long idField;
        
        private string keyField;
        
        private double latField;
        
        private double lngField;
        
        private bool locationKownField;
        
        private string nameField;
        
        private byte[] pictureBytesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
                this.RaisePropertyChanged("lat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double lng {
            get {
                return this.lngField;
            }
            set {
                this.lngField = value;
                this.RaisePropertyChanged("lng");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool locationKown {
            get {
                return this.locationKownField;
            }
            set {
                this.locationKownField = value;
                this.RaisePropertyChanged("locationKown");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] pictureBytes {
            get {
                return this.pictureBytesField;
            }
            set {
                this.pictureBytesField = value;
                this.RaisePropertyChanged("pictureBytes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shareSpot", WrapperNamespace="http://webservice.spotmap.de/")]
    public partial class shareSpotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.spotmap.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Spotmap.Webservice.spot arg0;
        
        public shareSpotRequest() {
        }
        
        public shareSpotRequest(Spotmap.Webservice.spot arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shareSpotResponse", WrapperNamespace="http://webservice.spotmap.de/")]
    public partial class shareSpotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.spotmap.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public shareSpotResponse() {
        }
        
        public shareSpotResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSharedSpot", WrapperNamespace="http://webservice.spotmap.de/")]
    public partial class getSharedSpotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.spotmap.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getSharedSpotRequest() {
        }
        
        public getSharedSpotRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSharedSpotResponse", WrapperNamespace="http://webservice.spotmap.de/")]
    public partial class getSharedSpotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.spotmap.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Spotmap.Webservice.spot @return;
        
        public getSharedSpotResponse() {
        }
        
        public getSharedSpotResponse(Spotmap.Webservice.spot @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shareSpots", WrapperNamespace="http://webservice.spotmap.de/")]
    public partial class shareSpotsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.spotmap.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Spotmap.Webservice.spot[] arg0;
        
        public shareSpotsRequest() {
        }
        
        public shareSpotsRequest(Spotmap.Webservice.spot[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="shareSpotsResponse", WrapperNamespace="http://webservice.spotmap.de/")]
    public partial class shareSpotsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.spotmap.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public shareSpotsResponse() {
        }
        
        public shareSpotsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSharedSpots", WrapperNamespace="http://webservice.spotmap.de/")]
    public partial class getSharedSpotsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.spotmap.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getSharedSpotsRequest() {
        }
        
        public getSharedSpotsRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSharedSpotsResponse", WrapperNamespace="http://webservice.spotmap.de/")]
    public partial class getSharedSpotsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.spotmap.de/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Spotmap.Webservice.spot[] @return;
        
        public getSharedSpotsResponse() {
        }
        
        public getSharedSpotsResponse(Spotmap.Webservice.spot[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpotShareChannel : Spotmap.Webservice.ISpotShare, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class shareSpotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public shareSpotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getSharedSpotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getSharedSpotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Spotmap.Webservice.spot Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Spotmap.Webservice.spot)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class shareSpotsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public shareSpotsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getSharedSpotsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getSharedSpotsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Spotmap.Webservice.spot[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Spotmap.Webservice.spot[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpotShareClient : System.ServiceModel.ClientBase<Spotmap.Webservice.ISpotShare>, Spotmap.Webservice.ISpotShare {
        
        private BeginOperationDelegate onBeginshareSpotDelegate;
        
        private EndOperationDelegate onEndshareSpotDelegate;
        
        private System.Threading.SendOrPostCallback onshareSpotCompletedDelegate;
        
        private BeginOperationDelegate onBegingetSharedSpotDelegate;
        
        private EndOperationDelegate onEndgetSharedSpotDelegate;
        
        private System.Threading.SendOrPostCallback ongetSharedSpotCompletedDelegate;
        
        private BeginOperationDelegate onBeginshareSpotsDelegate;
        
        private EndOperationDelegate onEndshareSpotsDelegate;
        
        private System.Threading.SendOrPostCallback onshareSpotsCompletedDelegate;
        
        private BeginOperationDelegate onBegingetSharedSpotsDelegate;
        
        private EndOperationDelegate onEndgetSharedSpotsDelegate;
        
        private System.Threading.SendOrPostCallback ongetSharedSpotsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SpotShareClient() : 
                base(SpotShareClient.GetDefaultBinding(), SpotShareClient.GetDefaultEndpointAddress()) {
        }
        
        public SpotShareClient(EndpointConfiguration endpointConfiguration) : 
                base(SpotShareClient.GetBindingForEndpoint(endpointConfiguration), SpotShareClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public SpotShareClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SpotShareClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public SpotShareClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SpotShareClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public SpotShareClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<shareSpotCompletedEventArgs> shareSpotCompleted;
        
        public event System.EventHandler<getSharedSpotCompletedEventArgs> getSharedSpotCompleted;
        
        public event System.EventHandler<shareSpotsCompletedEventArgs> shareSpotsCompleted;
        
        public event System.EventHandler<getSharedSpotsCompletedEventArgs> getSharedSpotsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Spotmap.Webservice.ISpotShare.BeginshareSpot(Spotmap.Webservice.shareSpotRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginshareSpot(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginshareSpot(Spotmap.Webservice.spot arg0, System.AsyncCallback callback, object asyncState) {
            Spotmap.Webservice.shareSpotRequest inValue = new Spotmap.Webservice.shareSpotRequest();
            inValue.arg0 = arg0;
            return ((Spotmap.Webservice.ISpotShare)(this)).BeginshareSpot(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Spotmap.Webservice.shareSpotResponse Spotmap.Webservice.ISpotShare.EndshareSpot(System.IAsyncResult result) {
            return base.Channel.EndshareSpot(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndshareSpot(System.IAsyncResult result) {
            Spotmap.Webservice.shareSpotResponse retVal = ((Spotmap.Webservice.ISpotShare)(this)).EndshareSpot(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginshareSpot(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Spotmap.Webservice.spot arg0 = ((Spotmap.Webservice.spot)(inValues[0]));
            return this.BeginshareSpot(arg0, callback, asyncState);
        }
        
        private object[] OnEndshareSpot(System.IAsyncResult result) {
            string retVal = this.EndshareSpot(result);
            return new object[] {
                    retVal};
        }
        
        private void OnshareSpotCompleted(object state) {
            if ((this.shareSpotCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.shareSpotCompleted(this, new shareSpotCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void shareSpotAsync(Spotmap.Webservice.spot arg0) {
            this.shareSpotAsync(arg0, null);
        }
        
        public void shareSpotAsync(Spotmap.Webservice.spot arg0, object userState) {
            if ((this.onBeginshareSpotDelegate == null)) {
                this.onBeginshareSpotDelegate = new BeginOperationDelegate(this.OnBeginshareSpot);
            }
            if ((this.onEndshareSpotDelegate == null)) {
                this.onEndshareSpotDelegate = new EndOperationDelegate(this.OnEndshareSpot);
            }
            if ((this.onshareSpotCompletedDelegate == null)) {
                this.onshareSpotCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnshareSpotCompleted);
            }
            base.InvokeAsync(this.onBeginshareSpotDelegate, new object[] {
                        arg0}, this.onEndshareSpotDelegate, this.onshareSpotCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Spotmap.Webservice.ISpotShare.BegingetSharedSpot(Spotmap.Webservice.getSharedSpotRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetSharedSpot(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetSharedSpot(string arg0, System.AsyncCallback callback, object asyncState) {
            Spotmap.Webservice.getSharedSpotRequest inValue = new Spotmap.Webservice.getSharedSpotRequest();
            inValue.arg0 = arg0;
            return ((Spotmap.Webservice.ISpotShare)(this)).BegingetSharedSpot(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Spotmap.Webservice.getSharedSpotResponse Spotmap.Webservice.ISpotShare.EndgetSharedSpot(System.IAsyncResult result) {
            return base.Channel.EndgetSharedSpot(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private Spotmap.Webservice.spot EndgetSharedSpot(System.IAsyncResult result) {
            Spotmap.Webservice.getSharedSpotResponse retVal = ((Spotmap.Webservice.ISpotShare)(this)).EndgetSharedSpot(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetSharedSpot(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string arg0 = ((string)(inValues[0]));
            return this.BegingetSharedSpot(arg0, callback, asyncState);
        }
        
        private object[] OnEndgetSharedSpot(System.IAsyncResult result) {
            Spotmap.Webservice.spot retVal = this.EndgetSharedSpot(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetSharedSpotCompleted(object state) {
            if ((this.getSharedSpotCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getSharedSpotCompleted(this, new getSharedSpotCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getSharedSpotAsync(string arg0) {
            this.getSharedSpotAsync(arg0, null);
        }
        
        public void getSharedSpotAsync(string arg0, object userState) {
            if ((this.onBegingetSharedSpotDelegate == null)) {
                this.onBegingetSharedSpotDelegate = new BeginOperationDelegate(this.OnBegingetSharedSpot);
            }
            if ((this.onEndgetSharedSpotDelegate == null)) {
                this.onEndgetSharedSpotDelegate = new EndOperationDelegate(this.OnEndgetSharedSpot);
            }
            if ((this.ongetSharedSpotCompletedDelegate == null)) {
                this.ongetSharedSpotCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetSharedSpotCompleted);
            }
            base.InvokeAsync(this.onBegingetSharedSpotDelegate, new object[] {
                        arg0}, this.onEndgetSharedSpotDelegate, this.ongetSharedSpotCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Spotmap.Webservice.ISpotShare.BeginshareSpots(Spotmap.Webservice.shareSpotsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginshareSpots(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginshareSpots(Spotmap.Webservice.spot[] arg0, System.AsyncCallback callback, object asyncState) {
            Spotmap.Webservice.shareSpotsRequest inValue = new Spotmap.Webservice.shareSpotsRequest();
            inValue.arg0 = arg0;
            return ((Spotmap.Webservice.ISpotShare)(this)).BeginshareSpots(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Spotmap.Webservice.shareSpotsResponse Spotmap.Webservice.ISpotShare.EndshareSpots(System.IAsyncResult result) {
            return base.Channel.EndshareSpots(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndshareSpots(System.IAsyncResult result) {
            Spotmap.Webservice.shareSpotsResponse retVal = ((Spotmap.Webservice.ISpotShare)(this)).EndshareSpots(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginshareSpots(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Spotmap.Webservice.spot[] arg0 = ((Spotmap.Webservice.spot[])(inValues[0]));
            return this.BeginshareSpots(arg0, callback, asyncState);
        }
        
        private object[] OnEndshareSpots(System.IAsyncResult result) {
            string retVal = this.EndshareSpots(result);
            return new object[] {
                    retVal};
        }
        
        private void OnshareSpotsCompleted(object state) {
            if ((this.shareSpotsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.shareSpotsCompleted(this, new shareSpotsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void shareSpotsAsync(Spotmap.Webservice.spot[] arg0) {
            this.shareSpotsAsync(arg0, null);
        }
        
        public void shareSpotsAsync(Spotmap.Webservice.spot[] arg0, object userState) {
            if ((this.onBeginshareSpotsDelegate == null)) {
                this.onBeginshareSpotsDelegate = new BeginOperationDelegate(this.OnBeginshareSpots);
            }
            if ((this.onEndshareSpotsDelegate == null)) {
                this.onEndshareSpotsDelegate = new EndOperationDelegate(this.OnEndshareSpots);
            }
            if ((this.onshareSpotsCompletedDelegate == null)) {
                this.onshareSpotsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnshareSpotsCompleted);
            }
            base.InvokeAsync(this.onBeginshareSpotsDelegate, new object[] {
                        arg0}, this.onEndshareSpotsDelegate, this.onshareSpotsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Spotmap.Webservice.ISpotShare.BegingetSharedSpots(Spotmap.Webservice.getSharedSpotsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetSharedSpots(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetSharedSpots(string arg0, System.AsyncCallback callback, object asyncState) {
            Spotmap.Webservice.getSharedSpotsRequest inValue = new Spotmap.Webservice.getSharedSpotsRequest();
            inValue.arg0 = arg0;
            return ((Spotmap.Webservice.ISpotShare)(this)).BegingetSharedSpots(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Spotmap.Webservice.getSharedSpotsResponse Spotmap.Webservice.ISpotShare.EndgetSharedSpots(System.IAsyncResult result) {
            return base.Channel.EndgetSharedSpots(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private Spotmap.Webservice.spot[] EndgetSharedSpots(System.IAsyncResult result) {
            Spotmap.Webservice.getSharedSpotsResponse retVal = ((Spotmap.Webservice.ISpotShare)(this)).EndgetSharedSpots(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetSharedSpots(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string arg0 = ((string)(inValues[0]));
            return this.BegingetSharedSpots(arg0, callback, asyncState);
        }
        
        private object[] OnEndgetSharedSpots(System.IAsyncResult result) {
            Spotmap.Webservice.spot[] retVal = this.EndgetSharedSpots(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetSharedSpotsCompleted(object state) {
            if ((this.getSharedSpotsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getSharedSpotsCompleted(this, new getSharedSpotsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getSharedSpotsAsync(string arg0) {
            this.getSharedSpotsAsync(arg0, null);
        }
        
        public void getSharedSpotsAsync(string arg0, object userState) {
            if ((this.onBegingetSharedSpotsDelegate == null)) {
                this.onBegingetSharedSpotsDelegate = new BeginOperationDelegate(this.OnBegingetSharedSpots);
            }
            if ((this.onEndgetSharedSpotsDelegate == null)) {
                this.onEndgetSharedSpotsDelegate = new EndOperationDelegate(this.OnEndgetSharedSpots);
            }
            if ((this.ongetSharedSpotsCompletedDelegate == null)) {
                this.ongetSharedSpotsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetSharedSpotsCompleted);
            }
            base.InvokeAsync(this.onBegingetSharedSpotsDelegate, new object[] {
                        arg0}, this.onEndgetSharedSpotsDelegate, this.ongetSharedSpotsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Spotmap.Webservice.ISpotShare CreateChannel() {
            return new SpotShareClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.SpotShareImplPort)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.SpotShareImplPort)) {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.72:8080/spotShare");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return SpotShareClient.GetBindingForEndpoint(EndpointConfiguration.SpotShareImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return SpotShareClient.GetEndpointAddress(EndpointConfiguration.SpotShareImplPort);
        }
        
        private class SpotShareClientChannel : ChannelBase<Spotmap.Webservice.ISpotShare>, Spotmap.Webservice.ISpotShare {
            
            public SpotShareClientChannel(System.ServiceModel.ClientBase<Spotmap.Webservice.ISpotShare> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginshareSpot(Spotmap.Webservice.shareSpotRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("shareSpot", _args, callback, asyncState);
                return _result;
            }
            
            public Spotmap.Webservice.shareSpotResponse EndshareSpot(System.IAsyncResult result) {
                object[] _args = new object[0];
                Spotmap.Webservice.shareSpotResponse _result = ((Spotmap.Webservice.shareSpotResponse)(base.EndInvoke("shareSpot", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetSharedSpot(Spotmap.Webservice.getSharedSpotRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getSharedSpot", _args, callback, asyncState);
                return _result;
            }
            
            public Spotmap.Webservice.getSharedSpotResponse EndgetSharedSpot(System.IAsyncResult result) {
                object[] _args = new object[0];
                Spotmap.Webservice.getSharedSpotResponse _result = ((Spotmap.Webservice.getSharedSpotResponse)(base.EndInvoke("getSharedSpot", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginshareSpots(Spotmap.Webservice.shareSpotsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("shareSpots", _args, callback, asyncState);
                return _result;
            }
            
            public Spotmap.Webservice.shareSpotsResponse EndshareSpots(System.IAsyncResult result) {
                object[] _args = new object[0];
                Spotmap.Webservice.shareSpotsResponse _result = ((Spotmap.Webservice.shareSpotsResponse)(base.EndInvoke("shareSpots", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetSharedSpots(Spotmap.Webservice.getSharedSpotsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getSharedSpots", _args, callback, asyncState);
                return _result;
            }
            
            public Spotmap.Webservice.getSharedSpotsResponse EndgetSharedSpots(System.IAsyncResult result) {
                object[] _args = new object[0];
                Spotmap.Webservice.getSharedSpotsResponse _result = ((Spotmap.Webservice.getSharedSpotsResponse)(base.EndInvoke("getSharedSpots", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            SpotShareImplPort,
        }
    }
}
