#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Spotmap.Droid.Resource", IsApplication=true)]

namespace Spotmap.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahBarColor = global::Spotmap.Droid.Resource.Attribute.ahBarColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahBarLength = global::Spotmap.Droid.Resource.Attribute.ahBarLength;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahBarWidth = global::Spotmap.Droid.Resource.Attribute.ahBarWidth;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahCircleColor = global::Spotmap.Droid.Resource.Attribute.ahCircleColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahDelayMillis = global::Spotmap.Droid.Resource.Attribute.ahDelayMillis;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahRadius = global::Spotmap.Droid.Resource.Attribute.ahRadius;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahRimColor = global::Spotmap.Droid.Resource.Attribute.ahRimColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahRimWidth = global::Spotmap.Droid.Resource.Attribute.ahRimWidth;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahSpinSpeed = global::Spotmap.Droid.Resource.Attribute.ahSpinSpeed;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahText = global::Spotmap.Droid.Resource.Attribute.ahText;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahTextColor = global::Spotmap.Droid.Resource.Attribute.ahTextColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahTextSize = global::Spotmap.Droid.Resource.Attribute.ahTextSize;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Drawable.ic_errorstatus = global::Spotmap.Droid.Resource.Drawable.ic_errorstatus;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Drawable.ic_successstatus = global::Spotmap.Droid.Resource.Drawable.ic_successstatus;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Drawable.roundedbg = global::Spotmap.Droid.Resource.Drawable.roundedbg;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Drawable.roundedbgdark = global::Spotmap.Droid.Resource.Drawable.roundedbgdark;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Id.loadingImage = global::Spotmap.Droid.Resource.Id.loadingImage;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Id.loadingProgressBar = global::Spotmap.Droid.Resource.Id.loadingProgressBar;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Id.loadingProgressWheel = global::Spotmap.Droid.Resource.Id.loadingProgressWheel;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Id.textViewStatus = global::Spotmap.Droid.Resource.Id.textViewStatus;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Layout.loading = global::Spotmap.Droid.Resource.Layout.loading;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Layout.loadingimage = global::Spotmap.Droid.Resource.Layout.loadingimage;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Layout.loadingprogress = global::Spotmap.Droid.Resource.Layout.loadingprogress;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.String.ApplicationName = global::Spotmap.Droid.Resource.String.ApplicationName;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.String.Hello = global::Spotmap.Droid.Resource.String.Hello;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.String.library_name = global::Spotmap.Droid.Resource.String.library_name;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel = global::Spotmap.Droid.Resource.Styleable.ProgressWheel;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarColor = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarLength = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarWidth = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahCircleColor = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRadius = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRimColor = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRimWidth = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahText = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahTextColor = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahTextSize = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::Spotmap.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::Spotmap.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::Spotmap.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::Spotmap.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::Spotmap.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::Spotmap.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::Spotmap.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::Spotmap.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::Spotmap.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::Spotmap.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::Spotmap.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::Spotmap.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::Spotmap.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::Spotmap.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::Spotmap.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::Spotmap.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::Spotmap.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::Spotmap.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::Spotmap.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::Spotmap.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::Spotmap.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::Spotmap.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::Spotmap.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::Spotmap.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::Spotmap.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::Spotmap.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.choiceOffset = global::Spotmap.Droid.Resource.Attribute.choiceOffset;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.swipeActionLeft = global::Spotmap.Droid.Resource.Attribute.swipeActionLeft;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.swipeActionRight = global::Spotmap.Droid.Resource.Attribute.swipeActionRight;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.swipeAllowFling = global::Spotmap.Droid.Resource.Attribute.swipeAllowFling;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.swipeAnimationTime = global::Spotmap.Droid.Resource.Attribute.swipeAnimationTime;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.swipeBackView = global::Spotmap.Droid.Resource.Attribute.swipeBackView;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.swipeCloseAllItemsWhenMoveList = global::Spotmap.Droid.Resource.Attribute.swipeCloseAllItemsWhenMoveList;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.swipeDrawableChecked = global::Spotmap.Droid.Resource.Attribute.swipeDrawableChecked;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.swipeDrawableUnchecked = global::Spotmap.Droid.Resource.Attribute.swipeDrawableUnchecked;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.swipeFrontView = global::Spotmap.Droid.Resource.Attribute.swipeFrontView;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.swipeMode = global::Spotmap.Droid.Resource.Attribute.swipeMode;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.swipeOffsetLeft = global::Spotmap.Droid.Resource.Attribute.swipeOffsetLeft;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.swipeOffsetRight = global::Spotmap.Droid.Resource.Attribute.swipeOffsetRight;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.swipeOpenOnLongPress = global::Spotmap.Droid.Resource.Attribute.swipeOpenOnLongPress;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.swipeRevealDismissThreshold = global::Spotmap.Droid.Resource.Attribute.swipeRevealDismissThreshold;
			global::FortySevenDeg.SwipeListView.Resource.Attribute.swipeRevealDismissView = global::Spotmap.Droid.Resource.Attribute.swipeRevealDismissView;
			global::FortySevenDeg.SwipeListView.Resource.Id.both = global::Spotmap.Droid.Resource.Id.both;
			global::FortySevenDeg.SwipeListView.Resource.Id.choice = global::Spotmap.Droid.Resource.Id.choice;
			global::FortySevenDeg.SwipeListView.Resource.Id.dismiss = global::Spotmap.Droid.Resource.Id.dismiss;
			global::FortySevenDeg.SwipeListView.Resource.Id.left = global::Spotmap.Droid.Resource.Id.left;
			global::FortySevenDeg.SwipeListView.Resource.Id.none = global::Spotmap.Droid.Resource.Id.none;
			global::FortySevenDeg.SwipeListView.Resource.Id.reveal = global::Spotmap.Droid.Resource.Id.reveal;
			global::FortySevenDeg.SwipeListView.Resource.Id.revealDismiss = global::Spotmap.Droid.Resource.Id.revealDismiss;
			global::FortySevenDeg.SwipeListView.Resource.Id.right = global::Spotmap.Droid.Resource.Id.right;
			global::FortySevenDeg.SwipeListView.Resource.String.library_name = global::Spotmap.Droid.Resource.String.library_name;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView = global::Spotmap.Droid.Resource.Styleable.SwipeListView;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_choiceOffset = global::Spotmap.Droid.Resource.Styleable.SwipeListView_choiceOffset;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_swipeActionLeft = global::Spotmap.Droid.Resource.Styleable.SwipeListView_swipeActionLeft;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_swipeActionRight = global::Spotmap.Droid.Resource.Styleable.SwipeListView_swipeActionRight;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_swipeAllowFling = global::Spotmap.Droid.Resource.Styleable.SwipeListView_swipeAllowFling;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_swipeAnimationTime = global::Spotmap.Droid.Resource.Styleable.SwipeListView_swipeAnimationTime;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_swipeBackView = global::Spotmap.Droid.Resource.Styleable.SwipeListView_swipeBackView;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_swipeCloseAllItemsWhenMoveList = global::Spotmap.Droid.Resource.Styleable.SwipeListView_swipeCloseAllItemsWhenMoveList;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_swipeDrawableChecked = global::Spotmap.Droid.Resource.Styleable.SwipeListView_swipeDrawableChecked;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_swipeDrawableUnchecked = global::Spotmap.Droid.Resource.Styleable.SwipeListView_swipeDrawableUnchecked;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_swipeFrontView = global::Spotmap.Droid.Resource.Styleable.SwipeListView_swipeFrontView;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_swipeMode = global::Spotmap.Droid.Resource.Styleable.SwipeListView_swipeMode;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_swipeOffsetLeft = global::Spotmap.Droid.Resource.Styleable.SwipeListView_swipeOffsetLeft;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_swipeOffsetRight = global::Spotmap.Droid.Resource.Styleable.SwipeListView_swipeOffsetRight;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_swipeOpenOnLongPress = global::Spotmap.Droid.Resource.Styleable.SwipeListView_swipeOpenOnLongPress;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_swipeRevealDismissThreshold = global::Spotmap.Droid.Resource.Styleable.SwipeListView_swipeRevealDismissThreshold;
			global::FortySevenDeg.SwipeListView.Resource.Styleable.SwipeListView_swipeRevealDismissView = global::Spotmap.Droid.Resource.Styleable.SwipeListView_swipeRevealDismissView;
			global::KS21.MvvmCross.Plugins.ExifPictureChooser.Droid.Resource.String.ApplicationName = global::Spotmap.Droid.Resource.String.ApplicationName;
			global::KS21.MvvmCross.Plugins.ExifPictureChooser.Droid.Resource.String.Hello = global::Spotmap.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01002a
			public const int MvxBind = 2130772010;
			
			// aapt resource value: 0x7f01002e
			public const int MvxDropDownItemTemplate = 2130772014;
			
			// aapt resource value: 0x7f01002d
			public const int MvxItemTemplate = 2130772013;
			
			// aapt resource value: 0x7f01002b
			public const int MvxLang = 2130772011;
			
			// aapt resource value: 0x7f01002f
			public const int MvxSource = 2130772015;
			
			// aapt resource value: 0x7f01002c
			public const int MvxTemplate = 2130772012;
			
			// aapt resource value: 0x7f010021
			public const int ahBarColor = 2130772001;
			
			// aapt resource value: 0x7f010029
			public const int ahBarLength = 2130772009;
			
			// aapt resource value: 0x7f010028
			public const int ahBarWidth = 2130772008;
			
			// aapt resource value: 0x7f010026
			public const int ahCircleColor = 2130772006;
			
			// aapt resource value: 0x7f010025
			public const int ahDelayMillis = 2130772005;
			
			// aapt resource value: 0x7f010027
			public const int ahRadius = 2130772007;
			
			// aapt resource value: 0x7f010022
			public const int ahRimColor = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int ahRimWidth = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int ahSpinSpeed = 2130772004;
			
			// aapt resource value: 0x7f01001e
			public const int ahText = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int ahTextColor = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int ahTextSize = 2130772000;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010012
			public const int choiceOffset = 2130771986;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010018
			public const int swipeActionLeft = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int swipeActionRight = 2130771993;
			
			// aapt resource value: 0x7f01001d
			public const int swipeAllowFling = 2130771997;
			
			// aapt resource value: 0x7f01000f
			public const int swipeAnimationTime = 2130771983;
			
			// aapt resource value: 0x7f010015
			public const int swipeBackView = 2130771989;
			
			// aapt resource value: 0x7f010013
			public const int swipeCloseAllItemsWhenMoveList = 2130771987;
			
			// aapt resource value: 0x7f01001a
			public const int swipeDrawableChecked = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int swipeDrawableUnchecked = 2130771995;
			
			// aapt resource value: 0x7f010014
			public const int swipeFrontView = 2130771988;
			
			// aapt resource value: 0x7f010017
			public const int swipeMode = 2130771991;
			
			// aapt resource value: 0x7f010010
			public const int swipeOffsetLeft = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int swipeOffsetRight = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int swipeOpenOnLongPress = 2130771982;
			
			// aapt resource value: 0x7f01001c
			public const int swipeRevealDismissThreshold = 2130771996;
			
			// aapt resource value: 0x7f010016
			public const int swipeRevealDismissView = 2130771990;
			
			// aapt resource value: 0x7f010006
			public const int uiCompass = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int uiRotateGestures = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int uiScrollGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiTiltGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiZoomControls = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int useViewLifecycle = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int zOrderOnTop = 2130771981;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int common_action_bar_splitter = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int common_signin_btn_dark_text_default = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_signin_btn_dark_text_disabled = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_signin_btn_dark_text_focused = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int common_signin_btn_dark_text_pressed = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int common_signin_btn_default_background = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int common_signin_btn_light_text_default = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int common_signin_btn_light_text_disabled = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_signin_btn_light_text_focused = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_signin_btn_light_text_pressed = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int common_signin_btn_text_dark = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int common_signin_btn_text_light = 2130968587;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addspot = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Button_Default_Blue = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int buttonshape = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int buttonshape_disabeled = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int buttonshape_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_disabled_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_disabled_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_focus_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_focus_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_normal_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_icon_normal_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_icon_pressed_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_icon_pressed_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_disabled_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_disabled_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_disabled_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_focus_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_focus_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_normal_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_text_normal_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_text_pressed_dark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_text_pressed_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_errorstatus = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_plusone_medium_off_client = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_plusone_small_off_client = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_plusone_standard_off_client = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_plusone_tall_off_client = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_successstatus = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Icon = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int roundedbg = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int roundedbgdark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int splash = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int spotgpslist = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int spotlistwithoutgps = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int spotmap = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Tab_Addspot = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Tab_Spotgpslist = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Tab_Spotlistwithoutgps = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Tab_Spotmap = 2130837549;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MvxBindingTagUnique = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int both = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int bundlesharelistview = 2131099664;
			
			// aapt resource value: 0x7f060009
			public const int choice = 2131099657;
			
			// aapt resource value: 0x7f060017
			public const int deleteSpot = 2131099671;
			
			// aapt resource value: 0x7f06000a
			public const int dismiss = 2131099658;
			
			// aapt resource value: 0x7f06001b
			public const int getSharedSpot = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int getSharedSpots = 2131099676;
			
			// aapt resource value: 0x7f060001
			public const int hybrid = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int left = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int loadingImage = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int loadingProgressBar = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int loadingProgressWheel = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int map = 2131099670;
			
			// aapt resource value: 0x7f060002
			public const int none = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int normal = 2131099651;
			
			// aapt resource value: 0x7f06000e
			public const int pictureInfowindowPicture = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int pictureInfowindowSnippet = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int pictureInfowindowTitle = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int reveal = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int revealDismiss = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int right = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int satellite = 2131099652;
			
			// aapt resource value: 0x7f060019
			public const int shareSpot = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int shareSpots = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int showOnMap = 2131099672;
			
			// aapt resource value: 0x7f060015
			public const int singlemap = 2131099669;
			
			// aapt resource value: 0x7f060005
			public const int terrain = 2131099653;
			
			// aapt resource value: 0x7f060012
			public const int textViewStatus = 2131099666;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddSpotView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Custom_info_contents = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GetSharedSpotsBundleView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int GetSharedSpotView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Item_Spot = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Item_Spot_Selectable = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int loading = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int loadingimage = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int loadingprogress = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MainView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ShareKeyView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SingleSpotOnMapView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SplashScreen = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SpotDetailView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SpotGpsListView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SpotListView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SpotmapView = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int SpotDetail_Menu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int SpotGpsList_Menu = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int Spotmap_Menu = 2131230722;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050020
			public const int AddSpotViewChoosePictureBtn = 2131034144;
			
			// aapt resource value: 0x7f05001e
			public const int AddSpotViewHeaderLabel = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int AddSpotViewLabel = 2131034141;
			
			// aapt resource value: 0x7f050021
			public const int AddSpotViewSaveBtn = 2131034145;
			
			// aapt resource value: 0x7f05001f
			public const int AddSpotViewTakePictureBtn = 2131034143;
			
			// aapt resource value: 0x7f05001a
			public const int ApplicationName = 2131034138;
			
			// aapt resource value: 0x7f050037
			public const int GetSharedSpotViewCancelBtn = 2131034167;
			
			// aapt resource value: 0x7f050036
			public const int GetSharedSpotViewDownloadBtn = 2131034166;
			
			// aapt resource value: 0x7f050035
			public const int GetSharedSpotViewHeaderLabel = 2131034165;
			
			// aapt resource value: 0x7f050033
			public const int GetSharedSpotViewLabel = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int GetSharedSpotViewSaveBtn = 2131034164;
			
			// aapt resource value: 0x7f05003c
			public const int GetSharedSpotsBundleViewCancelBtn = 2131034172;
			
			// aapt resource value: 0x7f05003a
			public const int GetSharedSpotsBundleViewDownloadBtn = 2131034170;
			
			// aapt resource value: 0x7f050039
			public const int GetSharedSpotsBundleViewHeaderLabel = 2131034169;
			
			// aapt resource value: 0x7f050038
			public const int GetSharedSpotsBundleViewLabel = 2131034168;
			
			// aapt resource value: 0x7f05003b
			public const int GetSharedSpotsBundleViewSaveBtn = 2131034171;
			
			// aapt resource value: 0x7f050019
			public const int Hello = 2131034137;
			
			// aapt resource value: 0x7f05001c
			public const int MainViewLabel = 2131034140;
			
			// aapt resource value: 0x7f050031
			public const int ShareKeyViewHeaderLabel = 2131034161;
			
			// aapt resource value: 0x7f050030
			public const int ShareKeyViewLabel = 2131034160;
			
			// aapt resource value: 0x7f050032
			public const int ShareKeyViewOkBtn = 2131034162;
			
			// aapt resource value: 0x7f05002e
			public const int SingleSpotOnMapViewLabel = 2131034158;
			
			// aapt resource value: 0x7f050025
			public const int SpotDetailViewHeaderLabel = 2131034149;
			
			// aapt resource value: 0x7f050024
			public const int SpotDetailViewLabel = 2131034148;
			
			// aapt resource value: 0x7f050026
			public const int SpotDetailViewMenuDeleteOption = 2131034150;
			
			// aapt resource value: 0x7f05002f
			public const int SpotDetailViewMenuShareSpot = 2131034159;
			
			// aapt resource value: 0x7f050027
			public const int SpotDetailViewMenuShowOnMapOption = 2131034151;
			
			// aapt resource value: 0x7f05002b
			public const int SpotGpsListViewHeaderLabel = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int SpotGpsListViewLabel = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int SpotGpsListViewMenuShareSpotsOption = 2131034157;
			
			// aapt resource value: 0x7f050023
			public const int SpotListViewHeaderLabel = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int SpotListViewLabel = 2131034146;
			
			// aapt resource value: 0x7f050028
			public const int SpotmapViewLabel = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int SpotmapViewMenuGetSharedSpotOption = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int SpotmapViewMenuGetSharedSpotsBundleOption = 2131034154;
			
			// aapt resource value: 0x7f050014
			public const int auth_client_needs_enabling_title = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int auth_client_needs_installation_title = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int auth_client_needs_update_title = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int auth_client_play_services_err_notification_msg = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int auth_client_requested_by_msg = 2131034136;
			
			// aapt resource value: 0x7f050013
			public const int auth_client_using_bad_version_title = 2131034131;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_enable_button = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_enable_text = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_enable_title = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_install_button = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_install_text_phone = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_install_text_tablet = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_install_title = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_invalid_account_text = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_invalid_account_title = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_network_error_text = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_network_error_title = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_unknown_issue = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_play_services_unsupported_text = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_unsupported_title = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_update_button = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_update_text = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_update_title = 2131034119;
			
			// aapt resource value: 0x7f050011
			public const int common_signin_button_text = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int common_signin_button_text_long = 2131034130;
			
			// aapt resource value: 0x7f05001b
			public const int library_name = 2131034139;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			public static int[] MvxBinding = new int[] {
					2130772010,
					2130772011};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130772012};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130772015};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130772013,
					2130772014};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] ProgressWheel = new int[] {
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			public static int[] SwipeListView = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997};
			
			// aapt resource value: 4
			public const int SwipeListView_choiceOffset = 4;
			
			// aapt resource value: 10
			public const int SwipeListView_swipeActionLeft = 10;
			
			// aapt resource value: 11
			public const int SwipeListView_swipeActionRight = 11;
			
			// aapt resource value: 15
			public const int SwipeListView_swipeAllowFling = 15;
			
			// aapt resource value: 1
			public const int SwipeListView_swipeAnimationTime = 1;
			
			// aapt resource value: 7
			public const int SwipeListView_swipeBackView = 7;
			
			// aapt resource value: 5
			public const int SwipeListView_swipeCloseAllItemsWhenMoveList = 5;
			
			// aapt resource value: 12
			public const int SwipeListView_swipeDrawableChecked = 12;
			
			// aapt resource value: 13
			public const int SwipeListView_swipeDrawableUnchecked = 13;
			
			// aapt resource value: 6
			public const int SwipeListView_swipeFrontView = 6;
			
			// aapt resource value: 9
			public const int SwipeListView_swipeMode = 9;
			
			// aapt resource value: 2
			public const int SwipeListView_swipeOffsetLeft = 2;
			
			// aapt resource value: 3
			public const int SwipeListView_swipeOffsetRight = 3;
			
			// aapt resource value: 0
			public const int SwipeListView_swipeOpenOnLongPress = 0;
			
			// aapt resource value: 14
			public const int SwipeListView_swipeRevealDismissThreshold = 14;
			
			// aapt resource value: 8
			public const int SwipeListView_swipeRevealDismissView = 8;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
